### PR TITLE
feat: Post-event attendance update flow 

### PR DESCRIPTION
**Pull request by omarzone**
I have implemented a flow to automate attendance updates post-event completion. The flow is triggered when a Campaign's status changes to 'Completed' and performs the following actions:

Retrieves related records using a Get Records step.
Updates relevant records to 'Attended' status.
Sends feedback emails to participants.
The flow has been tested by updating a Campaign's status to 'Completed,' and it follows the correct sequence of processes as designed. Note that it was necessary to modify the Campaign object and temporarily disable the maximum capacity validation rule during testing. All records were updated correctly. The implementation is functional and ready for review.

### CODE REVIEW

**Comment by JonatanJSM** [comment]
Did you change any configuration of your org? 

The error is related to settings that must be activated 
@omarzone

**Comment by omarzone** [comment]
The merge already passes all validations, it was an error when testing. A permissions file was created that conflicted with the original project.
That file was removed

**Comment by JonatanJSM** [comment]
Will it change your flow? Because the email you have is a constant, and they should be the emails of the participants. @omarzone

**Comment by omarzone** [comment]
I have implemented a flow to automate attendance updates post-event completion. The flow is triggered when a Campaign's status changes to 'Completed' and performs the following actions:

- Retrieves related records using a Get Records step.
- Updates relevant records to "Asistió" status.
- Sends feedback emails to participants.

Additionally, the email content has been modified, and now the flow sends feedback emails to the participants' email addresses. The flow has been tested by updating a Campaign's status to 'Completed,' and it follows the correct sequence of processes as designed. Note that it was necessary to modify the Campaign object and temporarily disable the maximum capacity validation rule during testing. All records were updated correctly. The implementation is functional and ready for review.

**Comment by JonatanJSM** [comment]
If you have more than one person, the flow only sends an email to the last person on this list. @omarzone

**Comment by JonatanJSM** [comment]
I have three Campaing Members 
image
Only with Josh gets the Email. 


I tried another case, I tried with 3 different emails. It's the same situation.
image
@omarzone

**Comment by omarzone** [comment]
Corrected the flow to ensure that emails are sent to all participants. Previously, only the last person in the list was receiving the email. The issue was resolved by properly configuring the loop and email sending logic. Now, each campaign member receives a personalized email.

**Review by JonatanJSM — APPROVED** [review]

**Pull request merged**
