### PR TITLE
feat: Added profiles permissions and new student profile

### PR DESCRIPTION
**Pull request by Jsvela749**
Added custom objects and fields permissions to the profiles.
Solved issue that not allows to create new campaigns for available capacity always zero.

### CODE REVIEW

**Comment by JonatanJSM** [comment]
Changes to the Account object are not loaded  @Jsvela749

**Comment by Jsvela749** [comment]
Changes added. Removed Account non-existent fields references.

**Comment by JonatanJSM** [comment]
The event coordinator must be able to create campaigns.
image
Please review the requirements again.
I recommend that you log in as a user with that role so that you can review them.
image

**Comment by JonatanJSM** [comment]
You have to upload  the field of Account object 
"Institution and organizations "
@Jsvela749

**Comment by Jsvela749** [comment]
Hi! I removed it from the org where we develop, it shouldn't exist, also we have added the new profile and permissions

**Comment by JonatanJSM** [comment]
The system administrator profile must have access to all fields @Jsvela749

**Comment by JonatanJSM** [comment]
View checkbox to allow repots @Jsvela749

**Comment by Jsvela749** [comment]
Reviewed permissions to the profiles.

**Comment by Jsvela749** [comment]
Sorry, closed by error.
Reviewed profiles permissions.
Added new custom object requested by the flows teams.

**Comment by JonatanJSM** [comment]
Hello. @Jsvela749 

- [x] The system administrator must have access to all fields in custom objects and to the fields they added to standard objects.
image

- [x] The new costom object need a tab
image


It's all:).

**Comment by Jsvela749** [comment]
Added the system administrator profile and the requested tab.

**Pull request merged**
